apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-network-config-helper
  namespace: ai-network-config-helper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-network-config-helper
  template:
    metadata:
      labels:
        app: ai-network-config-helper
    spec:
      # Thêm imagePullSecrets ở đây
      imagePullSecrets:
        - name: github-registry-creds
      containers:
        - name: ai-network-config-helper
          image: register.vinhthai.io.vn/vinhtechlab/ai-network-config-helper/ai-network-config-helper:latest
          ports:
            - containerPort: 80
