apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3Rlci52aW5odGhhaS5pby52biI6eyJ1c2VybmFtZSI6InJvb3QiLCJwYXNzd29yZCI6ImdscGF0LUNJTWVpQ2s2RktxS3VsV2l6eThlUTI4Nk1RcDFPakVILjAxLjB3MTNkcnR2NSIsImF1dGgiOiJjbTl2ZERwbmJIQmhkQzFEU1UxbGFVTnJOa1pMY1V0MWJGZHBlbms0WlZFeU9EWk5VWEF4VDJwRlNDNHdNUzR3ZHpFelpISjBkalU9In19fQ==
kind: Secret
metadata:
  name: github-registry-creds
  namespace: ai-network-config-helper
type: kubernetes.io/dockerconfigjson
