apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ainetworkconfig-ingress
  namespace: ai-network-config-helper
spec:
  ingressClassName: nginx
  rules:
    - host: "ainetworkconfig.vinhthai.io.vn"
      http:
        paths:
          - backend:
              service:
                name: ai-network-config-helper 
                port:
                  number: 80
            path: /
            pathType: Prefix
