apiVersion: v1
kind: Service
metadata:
  name: ai-network-config-helper
  namespace: ai-network-config-helper
spec:
  # 'type' determines how the Service is exposed.
  # - ClusterIP (default): Exposes the service on an internal IP in the cluster.
  # - NodePort: Exposes the service on each Node’s IP at a static port.
  # - LoadBalancer: Exposes the service externally using a cloud provider’s load balancer.
  type: ClusterIP
  selector:
    # This selector needs to match the labels of the Pods in the Deployment.
    app: ai-network-config-helper
  ports:
    - protocol: TCP
      # The port on which the service is exposed.
      port: 80
      # The port on the Pods to forward traffic to.
      targetPort: 80
